### ISSUE TITLE
Meerdere textures laden niet

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#15]
Misschien doe ik het niet goed, maar als ik meerdere textured objecten heb dan krijgen ze allemaal de texture van het object dat hiërarchisch gezien het laagste is.

Deze issue is te reproduceren door de laatste versie van de game (met textured world bounds en terrain).

Ik krijg geen foutmeldingen van libpng; die zijn er wel als ik een file opgeef die niet bestaat.

**Comment by FerryT** [comment]
Hmm dat zou ik moeten testen; ik zal er morgen eens naar kijken.

**Comment by timvdalen** [comment]
Als je nog hulp nodig hebt met het testen sta ik op standby ;)

**Comment by FerryT** [comment]
oh was ik nog vergeten te zeggen: met de laatste pull request zou dat nu moeten werken. 

edit:
Hier is wat code wat je kan gebruiken om het te zien.

```
ObjectHandle box = Cuboid(Pd(3,3,0));
box->material = Materials::TexturedMaterial("het_een_of_andere_plaatje.png");
world.children.insert(box);
```

**Comment by timvdalen** [comment]
Ah geweldig, ik ga het gelijk testen. Wat was de oorzaak?

**Comment by FerryT** [comment]
Schijnbaar moet je iedere keer textures disablen nadat je ze gebruikt hebt

**Comment by timvdalen** [comment]
Hrm, ik krijg het nog niet helemaal werkend. Waarschijnlijk doe ik het verkeerd, zou je eens naar objects.h:113 (https://github.com/timvdalen/OGO-2.3/blob/master/src/game/objects.h#L113) willen kijken? Ik krijg nu (en zo zag het er bij Carl ook uit, behalve dat bij mij de kubus wel werkt) al mijn andere objecten oranje en de cube wel goed gekleurd.

Als ik showGrid op Terrain aan heb staan dan zie ik de juiste kleur lijnen, maar dat materiaal wordt ook gebruikt voor de tegels die er na komen. Ik zal eerst een goed kijken naar de unselect method.

**Comment by timvdalen** [comment]
Oh, had je comment even gemist. Daar ga ik mee aan de slag dan.

**Comment by FerryT** [comment]
Het is belangrijk dat je overal ObjectHandle en MaterialHandle gebruikt bij members anders werken de overridden methods niet. Ik check morgen wel of daar dingen fout gaan.

**Comment by timvdalen** [comment]
Ah. Ik ben bang dat ik daar vaak fouten heb gemaakt. Mag ik ook een Handle naar een derived Object gebruiken? Aangezien ik members van Terrain nodig heb.

We lopen er morgen dan wel even doorheen.

**Comment by FerryT** [comment]
Dit werd veroorzaakt door de volgorde waarin idngen geinitialiseerd worden. textures loaden moet zodra de renderpipe opgezet is. Het is bij deze gefixt.
