### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by Heightened** [timvdalen/OGO-2.3#16]
Bij het inladen van de textures gaat er iets fout op windows.
Compilen gaat goed, en het programma draait prima wanneer geen van de textures worden gevonden.
Als er wel textures ingeladen worden geeft het programma een unhandled exception (access violation) bij  "png_read_info(png, info);" op line 85 in image.cpp.

Mogelijk gerelateerd aan #15.

**Comment by FerryT** [comment]
Ik heb geen idee wat dit kan veroorzaken; libpng zou de error handeling intern moeten doen. Misschien falen longjumps in MSVC. Nouja ik kijk er morgen wel naar.

**Comment by FerryT** [comment]
Dit lag aan Carl's compiler
