### ISSUE TITLE
Camera en spelers grens-gedrag

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#21]
De speler moet nog gebound worden naar de bounds van de terrein. De camera mag niet direct naar beneden kijken om het huidige gedrag te voorkomen. De oplossingen hiervoor lijken me straightforward. Echter, om de oplossing te kunnen implementeren moet de controller (tenminste dat lijkt mij de logische plek om de bound af te dwingen) de bounds van het terrein weten. Dit kan via een parameter of de controller moet een variabele hebben met de bounds (of een pointer naar die variabele). De laatste oplossing lijkt me het beste. Wat vinden jullie?

Verder mag de camera niet onder het terrein staan. Hier zijn twee oplossingen voor, of je zorgt ervoor dat je de camera niet verder naar onder kan bewegen, of je verkleint de afstand tot de speler als je de camera naar onder beweegt. De laatste oplossing is ingewikkelder maar zie je wel vaker in games. (Voor als je niet snapt wat ik bedoel in de eerste paar seconden van [dit](http://www.youtube.com/watch?v=0PWTMzK96m4&feature=context-shows&list=SL) filmpje zie je dat de afstand tot de speler wordt verkleint als je camera op z-niveau van de grond is, zodat deze op dit niveau blijft maar je angle wel mee beweegt). Welke vinden jullie de beste oplossing? Ik denk dat de laatste methode wel de mooiste is :).

**Comment by KAYLukas** [comment]
Ik heb het laatste probleem geimplementeerd als in het filmpje nu. Ik weet alleen niet wat we willen met het eerste gedeelte, dus daar wil ik nog wel graag antwoord op :D

**Comment by FerryT** [comment]
De huidige camera standpunten kloppen gewoon nog niet. Bij de third person view moet hij over de linker of rechter schouder van het personage kijken. Hij kijkt nu naar de origin. Ik denk dat als de camera altijd net iets hoger dan dat punt staat hij simpelweg niet in de grond kan kijken. Bij first person view moet de camera simpelweg een stuk omhoog (ongeveer op oog hoogte dus). We zuden de verticale kijkhoek kunnen limiteren maarja ik vind dat nu nog niet echt belangrijk.

**Comment by KAYLukas** [comment]
Ik heb de verticale kijkhoek al gelimiteerd, en dat over schouder kijken, moet niet een ingewikkeld probleem zijn. Echter, heb ik de modellen nog niet ingeladen dus kon ik niet echt zien hoe het er uit moet zien. Maar ik kan misschien vanavond daar ff naar kijken. 

Ga jij maar bezig aan belangrijke dingen idd :P.

**Comment by KAYLukas** [comment]
Maar mijn vraag was meer of jullie het er mee eens zijn als ik een parameter toevoeg in de klasse controller waar de bounds in staan. (en misschien dan ook in de constructor)

**Comment by FerryT** [comment]
Dat mag je als constante aan de class toevoegen in de header

**Comment by KAYLukas** [comment]
Opgelost, is verwerkt
