### ISSUE TITLE
Muis moet een bepaalde snelheid hebben om de camera te kunnen veranderen

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#22]
Als je je muis heel langzaam beweegt, beweegt de camera helemaal niet (althans bij mij). Is dit gedrag dat wij willen? Is af en toe nog al irritant, omdat hij soms hakkelt. Hebben jullie dit probleem ook?

**Comment by FerryT** [comment]
Dit was bij design maar ik hoor van sommige mensen die ik niet nader zal noemen ten behoeve van Carl dat het stront irritant is. Ik zal kijken als ik tijd over heb dan zal ik d'r wat aan doen.

**Comment by KAYLukas** [comment]
Ik denk dat het probleem misschien ook aan het verschil in fps zit, aangezien we alles laten afhangen van je fps en mijn machine iets minder fps haalt zal hij wat meer moeite hebben om de camera te bewegen.

**Comment by timvdalen** [comment]
Dit is opgelost met de input class rewrite van vandaag.
