### ISSUE TITLE
Handle types van niet base classes

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#26]
Zouden jullie geen handles willen gebruiken van niet base classes? [bijvoorbeeld hier](https://github.com/timvdalen/OGO-2.3/blob/master/src/game/structures.h#L21)
De base class is dus de class die nergens van inherit. Als je types van handles van types gaat assignen gaat hij inplaats van de reference te kopieren het object eerst casten en daarna een kopie in de handle opslaan. Dat gaat echt fout als ik net replication ga inbouwen etc. Graag ObjectHandle gebruiken en casten wanneer je hem gaat gebruiken.

**Comment by timvdalen** [comment]
Volgens mij heb ik ze nu allemaal gehad.

**Comment by FerryT** [comment]
Ok, mooi!
