### ISSUE TITLE
Camera staat niet op de goede plaats

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#28]
In third person view kijkt de camera naar de origin van de speler. Het is de bedoeling dat de speler dan over zijn linker of rechter schouder kijkt, De camera target moet dus een stuk omhoog en de camera een stuk naar links of rechts.

In first person view staat de camera letterlijk op de origin; hij moet echter op oog hoogte staan.

**Comment by lucavanballegooijen** [comment]
Dit is vrij gemakkelijk te verhelpen.pos in movement.cpp verwijst naar de positie waarnaar gekeken wordt in 3rd person en de positie waarvandaan gekeken wordt in 1st person.Op het moment zet ik player.origin steeds gelijk aan pos.Als je dat veranderd met een offset zou alles goed moeten komen

**Comment by FerryT** [comment]
Ok, doe maar :)

**Comment by timvdalen** [comment]
@lucavanballegooijen Heb je hier al wat vooruitgang mee? Ik heb net wat geprobeerd, maar het verplaatsen van de camera heeft nog wat gevolgen voor het schieten en bouwen (aangezien de vector richting het doel wordt berekend vanuit de kijkrichting van de camera).

**Comment by timvdalen** [comment]
Gisteren en vandaag is dit opgelost.
