### ISSUE TITLE
Player namen in de hud

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#29]
Als we eenmaal iets van een player replication hebben zou het heel handig zijn dat de playernaam van de player in het vizier kenbaar word gemaakt aan de speler. Dan kunnen we zien of dat allemaal goed werkt.

**Comment by KAYLukas** [comment]
Ik wil wel ff daar  naar kijken, ik doe ook wel meteen een status-bar. De hud heeft nog een paar bugs trouwens, die fix ik ook wel als tim dat goed vindt?

**Comment by FerryT** [comment]
Zou je ze boven het hoofd van de players kunnen projecteren?

**Comment by KAYLukas** [comment]
Ja :)

Trouwens, er gaat bij mij iets mis als ik een material select. Als ik select() en direct unselect en dan een andere material inlaad dan is geen material ingeladen, althans hij tekent dat niets meer. Moet ik nog een functie aanroepen na unselect()?

**Comment by FerryT** [comment]
In principe hoef je nooit zelf select en unselect aan te roepen. ~~Ik weet niet hoe dat werkt in de hud echter.~~ Dat geld ook voor de hud. Wat probeer je te doen?

**Comment by timvdalen** [comment]
> De hud heeft nog een paar bugs trouwens

Van mij mag je ze fixen, maar wat is het probleem?

Voor de interface moet je even een nieuwe class die inherit van Widget aanmaken en die dan toevoegen aan de HUD (handigste is op dezelfde manier als voor de MessageDisplayer en de CrossHair).

> Zou je ze boven het hoofd van de players kunnen projecteren?

Ja, kijk even naar glutStrokeString()

> Ik weet niet hoe dat werkt in de hud echter.

In principe hebben Widgets ook een Material die ze doorgeven aan Object, maar voor transparantie is dat lastig, dus ik gebruik voor de MessageDisplayer (en ook de LaserBeam) een handmatige select() unselect() in render() (of in post/preRender(), dat weet ik even niet zeker).

**Comment by KAYLukas** [comment]
Ik had iets gevonden met dat object de viewport konden overschrijden maar ik kan het niet reproduceren. Dus die laat ik maar zo.

Als je switched naar een material texture vanaf een colortexture gaat het mis als je de colortexture disabled omdat die de transparantie op nul zet, ben ik net achter gekomen. Dus je moet eerst een witte collor texture inladen en dan pas je material texture...
Op 9 jun. 2012, om 12:59 heeft Tim van Dalen het volgende geschreven:

**Comment by FerryT** [comment]
dan moet je dat even in de unselect fixen ipv een gare hack te doen :D

**Comment by KAYLukas** [comment]
Ja of in de select van materialtexture fixen, want als material gewoon een kleur select gaat alles goed. We gebruiken toch niet materials om bijvoorbeeld een material texture extra groen te maken ofzo? Want dat kan je na de fix niet meer doen.
Op 9 jun. 2012, om 13:26 heeft Ferry Timmers het volgende geschreven:

**Comment by FerryT** [comment]
Check [deze](https://github.com/timvdalen/OGO-2.3/blob/master/src/game/materials.cpp#L158) regel: ik gok dat dat allemaal 1en moeten zijn.

**Comment by timvdalen** [comment]
Jawel, zie TwinMaterial. Ik heb eerder al een keer zoiets als waar jij aan denkt geïmplementeerd en terug gedraaid.

KAYLukas reply@reply.github.comschreef:

**Comment by KAYLukas** [comment]
Hoe kom ik aan de huidige player en het huidige team?

**Comment by KAYLukas** [comment]
Vanuit de hud?

**Comment by FerryT** [comment]
nog niet, dat komt later allemaal in de game class, maar voor nu zou je een externe variable kunnen gebruiken.

**Comment by KAYLukas** [comment]
Willen we dit voor elke speler hebben of alleen voor jezelf?

Want dan is billboarding de enige oplossing

Verder is de status-balk af, alleen is de code totaal niet zoals het hoort, maar voor elk material een nieuw object aangaan maken om die select te voorkomen, levert me nu zo'n 9 objecten op, wat veel werk is, en niet bepaald super nuttig.

**Comment by FerryT** [comment]
> Verder is de status-balk af, alleen is de code totaal niet zoals het hoort, maar voor elk material een nieuw object aangaan maken om die select te voorkomen, levert me nu zo'n 9 objecten op, wat veel werk is, en niet bepaald super nuttig.

Zie mijn voorgaande comments.

> Willen we dit voor elke speler hebben of alleen voor jezelf?

Als je crosshair op een speler staat hoef je zelf alleen maar zijn naam te zien. Ik zie niet in hoe billboarding daar nut in heeft: je kan gewoon een projectie van een punt boven het hoofd van de speler naar het 2d scherm gebruiken.

**Comment by timvdalen** [comment]
> je kan gewoon een projectie van een punt boven het hoofd van de speler naar het 2d scherm gebruiken.

Niet eens nodig, het kan gewoon in 3D met glutStrokeString()

**Comment by timvdalen** [comment]
> Verder is de status-balk af
> Wat doe die precies?

**Comment by KAYLukas** [comment]
Bij billboarding lijkt me hud niet de juiste plek om ze te tekenen, team lijkt mij dan de beste oplossing.

@FerryT Dan is het al enigzins logischer, maar je wil denk ik wel hebben dat de naam kleiner wordt als de speler waar je op richt verder weg staat. Dus met projectie verlies je je perspectief.

@timvdalen , Maar dan moet je wel nog zorgen dat je naam niet onder een hoek staat, dat noemen ze (volgens mij) billboarding. Anyway, is dat niet iets wat je in speler of in het team wil doen. Omdat hud meer een 2d klasse hebt lijkt mij dat niet de juiste manier.

**Comment by timvdalen** [comment]
Zeker, dat hoort niet thuis in de HUD maar in Player.

**Comment by FerryT** [comment]
> Dan is het al enigzins logischer, maar je wil denk ik wel hebben dat de naam kleiner wordt als de speler waar je op richt verder weg staat. Dus met projectie verlies je je perspectief.

Persoonlijk vind ik dat juist fijner. Dat werkt bij de meeste shooters zo trouwens. Gewoon boven je crosshair de player name. Maarja ik dacht dat een projectie wel leuk zou zijn.

**Comment by KAYLukas** [comment]
We hebben nu bij elke speler een naam er boven, als ik kan testen wanneer iemand geselecteerd is kunnen we de naam er alleen boven zetten bij de speler die geselecteerd is. Op zich moet de projectie toch gewoon kunnen door matrixmode om te zetten? Dat zal dan niet echt een probleem zijn.

**Comment by timvdalen** [comment]
Nee, het is goed mogelijk om te switchen (duurt alleen even). Ik zal nog eens kijken of ik kan detecteren in welke mode we zitten zodat ik in Widget::preRender() en Widget::postRender() evt kan switchen, zodat je een Widget ook buiten de HUD kunt gebruiken.

Nu zie ik trouwens niet in waarom je naar 2D mode wil switchen, of begrijp ik je helemaal verkeerd?

**Comment by FerryT** [comment]
switchen van 2d naar 3d mode en omgekeerd is _heel erg_ kostbaar. Dit moet je maar 1x doen per render cycle.

**Comment by timvdalen** [comment]
Op het moment doen we dat dan ook.

(Ik moet eens kijken of we al forcen dat HUD het laatste (of natuurlijk eerste, volgens mij komt alles er dan nog steeds overheen) wordt getekend, dan zouden we nog even kunnen kijken of we niet terug hoeven te wisselen.)

**Comment by KAYLukas** [comment]
Ik wilde naar 2d mode switchen omdat Ferry wilde dat de naam van de speler altijd even groot ongeacht de afstand tot de speler. Op het moment is het gewoon een string boven de speler die dus vatbaar is voor perspectief. Op zich is dat ook niet meteen ongangbaar voor veel spellen. Maar als je hem in projection mode zou zetten dan blijft hij even groot ongeacht de afstand.

Anyway, in mijn visie is er niets mis met de huidige manier van implementatie, dus gewoon in model view. Kijk zelf maar ff wat jullie van de huidige versie vinden.

**Comment by FerryT** [comment]
Begint al ergens op te lijken! Alleen moeten ze nog wel een stuk kleiner zijn.

**Comment by timvdalen** [comment]
https://dl.dropbox.com/u/12618006/GOTO/NPC.png

Wat mij betreft opgelost met 4f9661d96988ed2882021f857b91d55184ca4f6f.
