### ISSUE TITLE
Textures en models

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#30]
Ik denk dat we nu er wel aan toe zijn om ook het grafische gedeelte op orde te brengen. Carl heeft al als goed is de models van alle game elementen af. Wat nu nog rest is textures voor de modellen en textures voor de wereld zelf. Endaarna moeten ze worden toegevoegd aan de assets.
#### Inspiratie:

![TRON texture pack voor MineCraft](http://i.ytimg.com/vi/YJLOfO7Cpfk/0.jpg)
(**Check de [video](http://www.youtube.com/watch?v=rtqyw3yYflk)**)

[plaatje](http://www.imgbase.info/images/safe-wallpapers/tv_movies/tron/14765_tron.jpg)

**Comment by timvdalen** [comment]
Even een notitie voor de grond tiles: denk er aan dat de grid er nog overheen kan worden getekend, dus lijnen zoals in de afbeelding zichbaar zijn moeten wel inset zijn.

**Comment by timvdalen** [comment]
Update: Alleen het hoofdgebouw moet nog.

**Comment by timvdalen** [comment]
Update: Dit is bijna klaar, maar we missen nog een model en texture voor een muntje.

**Comment by timvdalen** [comment]
We hebben nu alle assets.
