### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#32]
Iets waar ik nog niet eerder aan gedacht heb. Hebben iets van een console nodig waar je chat berichten in kan typen. Ik neem aan dat dat onderdeel van de hud is?

**Comment by timvdalen** [comment]
Ja, ik was er al mee bezig. Ik maak een soort van popup ding wat op Enter de keyboard input pakt.

**Comment by FerryT** [comment]
Ok, cool!

**Comment by KAYLukas** [comment]
Jammer dat input_glut van alle letters een hoofdletter maakt en geen backspaces doorstuurt. Maar de widget ziet er al goed uit, op een paar hacky shit na ;)

**Comment by timvdalen** [comment]
Ja, die input moet ik nog even wat aan doen. Special chars worden niet op dezelfde manier doorgegeven. Backspace zal ik zo doen, dat is niet zo ingewikkeld. 

KAYLukas reply@reply.github.comschreef:

**Comment by FerryT** [comment]
Let op dat de input module een enum terug geeft, die kan je beter ook als zodanig gebruiken.

**Comment by timvdalen** [comment]
Hmm ja, dat had ik gezien. Wat ik nu doe is de numerieke waarde van de enum casten naar een char, aangezien je gewoon de normale scan codes aan houdt in je enum.
Hoe kan ik het verschil zien tussen de Button voor 'A' en de Button voor 'a'?

**Comment by FerryT** [comment]
Op dit moment niet helaas. Ik zal er ff een mode voor maken in de input module

**Comment by timvdalen** [comment]
Thanks, dan zoek ik even uit hoe ik dat het makkelijkste naar een char gecast krijg, met case support. Er zijn geen andere scancodes voor lower/uppercase toch?

**Comment by FerryT** [comment]
Check input.grabText en input.onText.
ik heb hem btw niet getest, dus als er foutjes in zitten dan hoor ik het wel. :)

**Comment by timvdalen** [comment]
Hmm, nu heb je dus als ik het goed begrijp een interne buffer in de input klasse die wordt doorgegeven als je de text released? Want dat werkt niet, de HUD heeft ook een buffer (en daar is die nodig om de buffer op het scherm te tonen) dus die moet elke keypress worden geupdate.

**Comment by FerryT** [comment]
de buffer is niet intern, je kan input.text ook direct uitlezen.

**Comment by timvdalen** [comment]
Met de nieuwe input werkt de normale movement niet meer bij mij (de robot begint te bewegen als je een key loslaat in plaats van indrukt en stopt daarna ook niet meer) . Ik revert je commit voor nu even.

**Comment by FerryT** [comment]
Ik kan het niet repliceren. Gaat het fout bij mergen misschien?

**Comment by timvdalen** [comment]
Nee, alles kwam er clean in. Dit is op Windows, zal Linux even testen.

**Comment by FerryT** [comment]
Zowel op windows als op linux werkt het bij mij, ik zal hem opnieuw committen. Mischien heb ik niet alle files geadd.

**Comment by timvdalen** [comment]
Ik zie net dat als ik clean het niet werkt omdat in de main btnEnter 
nog gebruikt wordt. Kan het zijn dat je de main vergeten was?
Ferry Timmers schreef op 2012-06-10 15:56:

**Comment by FerryT** [comment]
jups, dat zal het geweest zijn.

**Comment by FerryT** [comment]
kan je die revert even unreverten?

**Comment by timvdalen** [comment]
Done

Ferry Timmers schreef op 2012-06-10 16:20:

**Comment by FerryT** [comment]
ok thanks!

**Comment by timvdalen** [comment]
Zo, met commit 4f9661d96988ed2882021f857b91d55184ca4f6f is dit opgelost. Als we behalve chat ook commando's mogelijk willen maken kunnen we daarvoor de functie op Input::onText gebruiken (op het moment main.cpp:getInput). Op het moment maak ik daar van alles gewoon een chat message, maar daar kunnen we natuurlijk zoeken naar een ! of een /.

**Comment by FerryT** [comment]
Ah, mooi nu kan ik die gebruiken ipv gaar een console schermpje op de achtergrond te gebruiken :D
Ik had al een idee hoe we het kunnen doen:
In game heb ik commando's gedefineerd die je als string kan aanroepen. Ik ben ook van plan om een commando te maken wat de console opent met al een commando half ingevuld. Dan kan je zowel 'say' en 'teamsay' met hetzelfde commando doen. Optie twee is dat je kan kijken of hetgeen wat de player ingevuld heeft een commando is (daar is ook een functie voor) en zo niet het als chat te zien. De laatste optie is idd met een / of ! ervoor.

**Comment by timvdalen** [comment]
Ik was al bezig met een prompt variabele in TextInput, dus dan kunnen we die daar mooi gebruiken.
