### ISSUE TITLE
Robot model werkt niet goed

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#33]
Na mijn laatste commit is het robot model opgeblazen:

![Problem](https://dl.dropbox.com/u/40912731/Schermafbeelding%202012-06-09%20om%2016.11.46.png)

Als ik mijn laatste commit revert, kan ik heb hem dan later weer invoeren? Ik zie de fout echt niet waardoor dit is gekomen. Zelfs als ik al mijn nieuwe features uit comment heb ik het probleem nog steeds... Zien jullie dit ook?

**Comment by timvdalen** [comment]
Ja, ik zie hetzelfde als jij.

Denk er trouwens aan dat als je numeric_limits gebruikt je <limits> include. Misschien ligt het aan mijn versie van GCC maar op mijn desktop en mijn laptop is die include nodig.

**Comment by KAYLukas** [comment]
Ow okay, bij mij pakt hij die dus zonder problemen. Waar mis je hem?

Het probleem ontstaat bij het aanmaken van een nieuwe player en een nieuw team. Iemand enig idee hoe dat kan?

**Comment by timvdalen** [comment]
movement.cpp
Ik zal mijn change niet commiten voor als je nog makkelijk wilt kunnen reverten.
Hmm, moet je even aan @Heightened vragen, die heeft een functie gemaakt om robot onderdelen tov de origin van de speler te transleren.

**Comment by KAYLukas** [comment]
Bij de commit staat welke regel dit veroorzaakt, kan iemand misschien kijken hoe dat kan?

**Comment by KAYLukas** [comment]
Je mag hem wel committen, ik weet toch precies nu waar de fout vandaan komt.

**Comment by KAYLukas** [comment]
Ik denk dat ik ongeveer weet wat er gebeurd. @Heightened transleer de robot onderdelen als je een speler aanmaakt, echter wijst hij aan elke robot hetzelfde onderdeel toe, waardoor je dus alle onderdelen transleert, ook die van de andere speler aangezien die gewoon precies hetzelfde is. Nu zal de oplossing iets moeten zijn dat je het model loskoppelt van het object. Het object een pointer naar het model heeft, en het object gekopieerd kan worden zodat de origin los verschillend is per speler.

**Comment by FerryT** [comment]
Gewoon een extra object ertussen spawnen en het zou opgelost moeten zijn :)

```
head = Assets::HeadObj;
...
```

vervangen door

```
head = Object();
head.insert(Assets::HeadObj);
...
```

**Comment by FerryT** [comment]
dit zou nu gefixt moeten zijn, kijk maar ff.

**Comment by timvdalen** [comment]
Met de laatste versie van de code en de assets werkt het bij mij.
