### ISSUE TITLE
Selecteren van verschillende gebouwen

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#35]
De build-modus moet nog uitgebreid worden naar meerdere gebouwen. 
Ik heb zelf al een hud widget gemaakt die aangeeft welke gebouwen er zijn en hoe je ze selecteert.(Voor mine en tower)
Aleen moet dit ook nog in de build-modus verwerkt worden.

**Comment by FerryT** [comment]
Ze moeten uiteindelijk in [deze](https://github.com/timvdalen/OGO-2.3/blob/master/src/game/player.h#L27) enum komen te staan. Ze worden met [deze](https://github.com/timvdalen/OGO-2.3/blob/master/src/game/game.h#L88) functie geselecteerd.

**Comment by KAYLukas** [comment]
Hoe kan ik de naam van de tool opvragen uit de enum?

Ik heb bijvoorbeeld nu dit:

![Voorbeeld](https://dl.dropbox.com/u/40912731/Schermafbeelding%202012-06-10%20om%2023.16.05.png)
Dit is nu nog lelijk gedaan via hardcoding, maar eigenlijk wil ik dat met een for-loop doen. Dus dan wil je de naam van de build-modus, en het icoon ofzo kunnen opvragen (in principe gewoon welk gebouw er gebouwd wordt). Hoe kan ik dat het beste doen?

**Comment by KAYLukas** [comment]
Ow ja en natuurlijk de button die gepressed moet worden voor het gebouw.

**Comment by FerryT** [comment]
De knop opvragen lijkt me niet nodig, dat staat dadelijk in de handleiding. Bij de meeste shooters staat dat in een logische volgorde die overeen komt met de numerieke toetsen. Je kan geen namen opvragen van de enum, dat kan je met een switch statement doen.

```
switch (tool)
{
    case toolSomething:
        ...
        break;

    default:
        ...
        break;
}
```

**Comment by KAYLukas** [comment]
Hmm, okay, ik denk dat het handigste is om te wachten met het verder initialiseren van de widget totdat het selecteren geimplementeerd is.

**Comment by timvdalen** [comment]
Hadden we niet afgesproken dat als je over een mine heen bouwt dat je dan automatisch een gatherer bouwt en anders een tower?

**Comment by FerryT** [comment]
Ja maar dat was de 'tijdelijke' oplossing want Carl vond het niet zo nice.

**Comment by timvdalen** [comment]
Carl zei juist vanochtend tegen mij dat hij het raar vond dat we het nu met een menu deden terwijl we iets anders hadden afgesproken.

**Comment by KAYLukas** [comment]
Ow, nouja we kijken wel even wat we doen dan. Het is er heel simpel uitgehaald :P. Wel jammer van het werk :(.

Ik wist niet meer dat we dat hadden afgesproken.

Is wel irritant als je mis klikt dat je opeens een ander gebouw bouwt natuurlijk.

Ik had het idee van het menu gehaald uit de informele specificatie, daar hadden we namelijk gespecificeerd dat we een menu lieten zien in de bouw-modus.
Pagina 8:
https://dl.dropbox.com/u/40912731/documentation.pdf

Deden we niet zo iets omdat het minder werk zou zijn?

**Comment by KAYLukas** [comment]
Okay we doen nu de de andere manier zie ik? BuildingSelection hud kan weggehaald uitgecomment worden?

**Comment by timvdalen** [comment]
Ja, voor nu heb ik de andere manier gedaan. Ik kan het nog omzetten, maar haal de BuildingSelection nu maar uit de HUD (gewoon niet adden).
