### ISSUE TITLE
bug tijdens schieten

### ISSUE THREAD

**Issue by PeterKoymans** [timvdalen/OGO-2.3#36]
Als je schiet en tijdens het schieten met de robot draait, lijkt de laserbeam mee te draaien.

**Comment by timvdalen** [comment]
Dit kan ik niet reproduceren. Heb het even gechecked, maar de LaserBeam kopieert de richting van de camera en houdt er geen reference naar, dus tijdens een rotatie blijft de LaserBeam in dezelfde richting.
