### ISSUE TITLE
Player::list

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#37]
Ik wilde player::list gebruiken om over alle spelers te itereren. Echter, staat de huidige speler niet in de lijst, en ook de npc wordt verwijderd.

Om er achter te komen wat er gebeurde, heb ik bij de constructor en destructor (als dat zo heet) een printf statement gedaan met de naam en of hij verwijderd wordt of aan gemaakt wordt. Dit is de uitvoer van het programma:

```
playercreated
*** Listening on port 9070... ***
playercreated
playerdeleted
NPCcreated
NPCdeleted
playercreated
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
NPCdeleted
```

Kan iemand mij uitleggen waarom dit gebeurd? Een destructor wordt toch maar 1 keer per leven van het object uitgevoerd?

**Comment by KAYLukas** [comment]
De enige speler die overblijft is de speler waar de statusbalk aangekoppeld is. (Dit is nog een dummy speler)

**Comment by FerryT** [comment]
Ik geloof toch echt dat ik die member had weggegooit. Gebruik `game.players` voortaan. De reden dat de player constructir te vaak aan geroepen word is omdat op een aantal plaatsen hij by value wordt gepasst. Hij moet het liefst als const reference gepasst worden: `const Player &` in functies.

**Comment by KAYLukas** [comment]
Okay, ik zag al dat je hem gefixed had. In die lijst staan ook nog geen spelers, maar ik neem aan dat die lijst nog WIP is. Dus dan denk ik dat deze gefixed is.

**Comment by FerryT** [comment]
Als je verbinding maakt komt de verbindende spelers er al wel in als je moet testen :)
