### ISSUE TITLE
Op de grid klikken in first person mode returned -1, -1

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#39]
Als je in first person mode bent (automatisch of door inzoomen) tijdens bouwmode en op de grid klikt, returned Terrain::getGridCoordinates() altijd (-1, -1).

**Comment by KAYLukas** [comment]
Waarschijnlijk komt dit omdat de camera en de lookat object hetzelfde is, dus kan getGridCoordinates geen kijkvector construeren, waardoor hij -1,-1 moet terug geven. Dit moet opgelost worden door de kijkvector en het startpunt te geven in plaats van het punt waar deze naar kijkt of, een ander lookat object mee te geven.

**Comment by KAYLukas** [comment]
Een ander probleem is op het moment ook nog dat hij niet altijd de juiste coordinaten teruggeeft, sinds de camera is opgeschoven, hij lijkt ernamelijk vaak net naast te zitten

**Comment by KAYLukas** [comment]
Ik ben trouwens enigszins geschokt dat hij wel de een grid kan heighlighten in de first person mode, waarschijnlijk is de code niet consistent. Ofwel het heighlighten passeert andere aan getgridcoordinates parameters dan het bouwen.

**Comment by timvdalen** [comment]
> hij lijkt ernamelijk vaak net naast te zitten

Dit komt door een afrondingsfout. Toen @Heightened en ik bij OGO weg gingen had @FerryT die gevonden.

> waarschijnlijk is de code niet consistent

Dat had ik ook gemerkt ja. Die selectie had ik toevallig vanmiddag geupdate, dus heb er even naar gekeken. Daar heb ik de 'oude' manier (`cam.origin + -cam.objective * Vd(0,10,0)`) gebruikt, die niet Controller::target gebruikt.

**Comment by KAYLukas** [comment]
Waarom wil je eigenlijk niet gewoon cam.objective gebruiken? Camera staat toch ook in de controller?

Op 13 jun. 2012, om 00:28 heeft Tim van Dalen het volgende geschreven:

**Comment by timvdalen** [comment]
@lucavanballegooijen Had me aangeraden om die target te gebruiken.

**Comment by timvdalen** [comment]
Dit is opgelost met de nieuwe input class en @PeterKoymans rewrite van getGridCoordinates().
