### ISSUE TITLE
De namen van clients die later joinen worden niet naar eerdere clients verstuurd

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#4]
Situatie: Drie spelers, A, B en C.

Hoe te reproduceren:
A host een game.
B joined deze game.
C joined deze game.
B zegt: Test
A, B, en C zien dit bericht goed.
C zegt: Ook test.
A en C zien dit bericht goed, B heeft geen informatie over de naam van C, dus ziet: <>: Ook test.

**Comment by FerryT** [comment]
Ik heb hem gevonden, er zat een rotte macro in. Ik ga hem zo pushen
