### ISSUE TITLE
Hoe kom je aan een team

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#40]
Als ik een character heb van het team van een speler, hoe kan ik aan het corresponderende team komen?

**Comment by Heightened** [comment]
Wat bedoel je, de andere spelers in het team?
... specificeer even wat je bedoelt met team... want 'a' (rood) of 'b'
(blue) weet je al als je een character hebt...
Carl

On Wed, Jun 13, 2012 at 1:21 AM, KAYLukas
reply@reply.github.com
wrote:

**Comment by KAYLukas** [comment]
Het team object, zodat je de resources op kan vragen.
Op 13 jun. 2012 01:50 schreef "Carl van Dueren den Hollander" <
reply@reply.github.com>
het volgende:

**Comment by KAYLukas** [comment]
Lijkt me al opgelost nu. @timvdalen heeft de statusbar nu al gelinked als ik het goed heb

**Comment by timvdalen** [comment]
Ja, ik heb Game::game.teams gebruiken. Wie de statusbar gelinkt heeft weet ik niet, toen ik met geld en health bezig was zag ik dat de status bar ineens werkte, ik heb er niet aangezeten.
