### ISSUE TITLE
Z-move zorgt voor 'achteruitkijkspiegel'-view

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#42]
Als je [space] of c gebruikt om te bewegen over de Z as werkt de camera niet goed. De camera komt recht voor je, op jezelf gericht zodat je je eigen voorkant ziet (je hoofd is wel van je af gericht).

**Comment by timvdalen** [comment]
@lucavanballegooijen Heb je dit weekend tijd om hier even naar te kijken?

**Comment by lucavanballegooijen** [comment]
ivm verhuizing ouders, niet veel, maar kan t wel even doen, belangrijker is voor mij de vraag: is dit boeiend? Waar gebruiken we moveZ?Maar als je zegt: toch doen, dan fix ik het wel

**Comment by timvdalen** [comment]
Voor het testen zou het wel fijn zijn als je dit even wil fixen.

Luca van Ballegooijen reply@reply.github.comschreef:

**Comment by lucavanballegooijen** [comment]
Ok. 't is nu gefixt
