### ISSUE TITLE
FPS van message displayer

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#43]
We hadden het gisteren over de fps-lag die de message displayer veroorzaakt. Nu heb ik de message displayer verandert om stroke characters te gebruiken: waarbij ik deze fps haal:

![stroking](https://dl.dropbox.com/u/40912731/Schermafbeelding%202012-06-15%20om%2011.05.03.png)

En origineel haalde ik:
![bitmap](https://dl.dropbox.com/u/40912731/Schermafbeelding%202012-06-15%20om%2011.06.35.png)

Let op: Dit is in beide gevallen na het spammen van de fps knop om de minimap langer te laten zien om een zo groot mogelijke fps drop te krijgen. Zonder spammen haal ik in beide gevallen ±49fps.

Willen jullie dat ik deze versie van messagedisplayer commit?

**Comment by timvdalen** [comment]
Hmm. Ik zal van het weekend even kijken wat voor resultaten ik krijg. Monospace was heel handig voor de berekeningen. Commit dit maar niet, als ik iets vind dan zal ik het committen, wil dan toch nog even aan appearance en grootte sleutelen.

**Comment by timvdalen** [comment]
Zou je de code die je hiervoor hebt gebruikt even in een gist willen opslaan?

**Comment by KAYLukas** [comment]
Wat is een gist? Ik zal ff in dropbox kijken of ik hem kan terughalen.

**Comment by timvdalen** [comment]
https://gist.github.com/

**Comment by KAYLukas** [comment]
https://gist.github.com/2941881

**Comment by timvdalen** [comment]
Ik kan dit niet reproduceren. glutStrokeCharacter tekent eerst grote lijnen en die scalen we dan naar beneden. Dat ziet er niet mooi uit.
Het kan aan mijn general performance liggen, maar glutStrokeCharacter levert bij mij 57 FPS op en glutBitmapCharacter 58. Daarbij komt dat glutBitmapCharacter bedoeld is voor wat wij doen, 2D text printen op een overlay en glutStrokeCharacter niet.
