### ISSUE TITLE
Speler in playerlist beweegt automatisch

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#44]
Als ik de huidige speler toevoeg aan Game::game.playerlist dan gaat die speler automatisch bewegen. Als ik een andere speler toe voeg aan die lijst (in welke volgorde dan ook) gebeurt dit niet.

@FerryT Is dit een test of een bug?

**Comment by FerryT** [comment]
Dit komt door de simulatie code (player interpolation). Ik ga nu de main opruimen en alle initialisatie in zijn definitieve vorm zetten. Ik zal daarna ff kijken hoe dit op te lossen.

**Comment by timvdalen** [comment]
Ah, mooi om te horen. Ik ben nu aan het werk aan het bouwen, dus ik had owners nodig. Ik merk het wel als het opgelost is.

**Comment by FerryT** [comment]
gefixt
