### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#45]
Met de nieuwste commits compiled hij niet meer bij mij. Er lijkt iets mis te gaan bij de = operator in core.h:

![Compile error](https://dl.dropbox.com/u/40912731/Compile%20error.png)

Heeft mijn compiler niet dezelfde libraries als bij jullie of klopt er iets niet in de code?

**Comment by FerryT** [comment]
gefixed
