### ISSUE TITLE
New style collision

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#46]
Ik heb nu dus een iterator gemaakt die over objecten kan itereren incluis hun kinderen. Ik zou graag de collision zien via deze iterator. Ik heb al wat stubjes gemaakt (`World::trace` en `World::sense`) die ik graag wil implementeren. Er zijn nu twee dingen die anders moeten: de huidige collision function `BoundedObject::checkCollision` is nog recursief geimplementeerd; dat zou dan dus niet meer moeten. Verder heb je absoluete coordinaten en rotaties nodig. Ook daarvoor heb ik functies gemaakt (`Object::absoluteOrigin()` en `Object::absoluteRotation()`) alleen weet ik nog niet of ze kloppen. Verder moet `game.world->updateAbsolute()` aangeroepen worden voor de berekeningen. Technisch gezien hoeft dat alleen wanneer coordinaten worden gewijzigd, maar daar wil ik nu nog ff niet moeilijk over gaan doen.

Laatste ding: De tweede `checkCollision1 functie is nog niet helemaal geimplementeerd.

Als iemand hier ff naar wil kijken dan zou dat tof zijn!

**Comment by KAYLukas** [comment]
Fixed, I would say.
