### ISSUE TITLE
Status bar schaalt niet mee

### ISSUE THREAD

**Issue by FerryT** [timvdalen/OGO-2.3#47]
De mini map schaalt mooi mee als je het scherm vergroot of verkleint. Dit is misschien ook een leuk idee voor de status balk.

**Comment by KAYLukas** [comment]
Fixed, misschien ook nog een idee om het chatvenster mee te schalen. @timvdalen is dat een idee?

**Comment by timvdalen** [comment]
Het chatvenster schaalt al mee, daar had ik het schalen voor toegevoegd. (Of bedoel je niet de input maar de displayer? Want die moet nog wel ja)

**Comment by KAYLukas** [comment]
Ik bedoelde de displayer idd;)
