### ISSUE TITLE
HQ op minimap

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#49]
De HQ staat niet goed op de minimap weergegeven (waarschijnlijk omdat @KAYLukas dacht dat die op een andere GridPoint zou komen).

![error](https://dl.dropbox.com/u/12618006/GOTO/HQ.png)

**Comment by KAYLukas** [comment]
Ik zal er ff naar kijken, ik zag het al eerder maar vroeg me af of alles al goed geimplementeerd was.

**Comment by timvdalen** [comment]
Ja, dat staat nu allemaal. Uiteindelijk staat het gebouw zelf nu in de rechter bovenhoek van de 4 plekken die het inneemt.

**Comment by KAYLukas** [comment]
Fixed
