### ISSUE TITLE
Geld

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#50]
Het automatisch optellen van geld werkt niet, er wordt alleen constant het gemiddelde van genomen, dus zelfs het automatisch geld verdienen werkt niet.

**Comment by timvdalen** [comment]
Dat is redelijk by design atm geloof ik. Iedereen verdient het geld voor elk team en daarvan wordt het gemiddelde genomen. Als er niet gecheat wordt zou het dus moeten kloppen.
Misschien dat we zo even kunnen uitvinden waarom dit niet zo is.

**Comment by KAYLukas** [comment]
Ow zo. Ik dacht dat gemiddelde alleen gebruikt werd voor randgevallen, maar we gebruiken het dus ook hiervoor. Nouja, dan klopt het wel denk ik zo.

Wie is eigenlijk waar mee bezig?

P.S. Ik heb de interpolation zonet gefixed hij had 2 hele kleine foutjes, daardoor werkte hij niet.

**Comment by timvdalen** [comment]
Ik ben wat kleine gameplay dingen aan het doen (spawns etc) en de lobby aan het koppelen met de game (dat verbinding via lobby werkt).

KAYLukas reply@reply.github.comschreef:
