### ISSUE TITLE
Random segfault midden in het spel

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#52]
Ik zat net iets van 15 min in een 1vs1 spel toen ik een segfault kreeg. Ik runde niet in mijn debugger. Visual Studio probeerde nog in te haken maar had geen source, dus ik heb nog niet gevonden waar het aan ligt.

Volgens mij ben ik niet de enige met deze issue, jij had hem ook al gezien, toch @FerryT?

**Comment by PeterKoymans** [comment]
Hier hebben we deze middag nog uitvoerig op getest. Volgens mij is de oorzaak dat een player null is.
