### ISSUE TITLE
Network Discovery

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#53]
Network discovery zou als het goed is nu moeten werken. Je kan 'Discover' in typen voor de lijst met spelers waar je mee kan verbinden. Deze zijn met een integer genummerd. Via join kan je dan die integer intypen en dan connect je automatisch. Je kan niet met jezelf verbinden. (Dat is heel lelijk geimplementeerd xD).

Elke seconde wordt een broadcast gestuurd dat jij er bent met ongeveer 20-30 characters afhankelijk van je naam. Bij een disconnect van 5 seconden wordt je uit de lijst verwijderd.

Ik heb het getest op mac en windows. Maar zouden jullie, wie nog wakker is, ff kunnen kijken of het ook werkt bij jullie?

**Comment by KAYLukas** [comment]
Verder heb ik nog een vraagje, in de gebruikershandleiding staat de lobby beschreven. Willen we dat daar laten, want het is een leuke beschrijving, maar als hij het niet kan gebruiken is het nogal onnuttig... Anders vervang ik het door de ingame network discovery.

**Comment by timvdalen** [comment]
Ik zou zeggen dat we die er in laten. Het programma werkt op zich redelijk. Misschien alleen aanvullen met deze nieuwe manier.

**Comment by KAYLukas** [comment]
We hebben het gisteravond al helemaal aan zitten passen. Omdat 'redelijk' (op mac en windows meer zoiets is van 'niet') en hem compleet verward zodat hij het spel niet eens werkend krijgt.

**Comment by timvdalen** [comment]
Hmm ok. Wel zonde van het werk aan de lobby. Jammer dat we die dan niet in kunnen leveren, maar ik zal er nog eens naar kijken de komende tijd.
