### ISSUE TITLE
Renames versus kopiëren

### ISSUE THREAD

**Issue by timvdalen** [timvdalen/OGO-2.3#54]
Nu OGO voorbij is wil ik de repository graag renamen naar GOTO.

Dat kan op twee manieren:
- Echt renamen. Dan werkt de oude link niet meer en moeten jullie je remotes updaten.
- Een nieuwe repo op basis van deze. De git history blijft bewaard, maar de issues en de wiki niet, die horen bij github. De wiki overzetten is natuurlijk triviaal, maar de issues niet.

De eerste leek me eerst vervelend als we Hoogerwoord een link hadden gegeven, maar als ik het goed heb hebben we dat niet meer gedaan, dus dan zou dat denk ik de best optie zijn.

**Comment by KAYLukas** [comment]
De laatste optie is in principe een fork, toch?

**Comment by timvdalen** [comment]
Ja, sortof. Ik begin meer naar optie 1 te leunen aangezien niemand de oude link had.
Dan maak ik desnoods een nieuwe repo OGO-2.3 met een history kopie en een link naar de nieuwe, maar dat lijkt me niet echt nodig.

KAYLukas reply@reply.github.comschreef:

**Comment by FerryT** [comment]
Ik zat meer aan een kopie te denken omdat we dan alle niet relevante dingen uit de history kunnen halen. Ook lijkt me het verstandig om over te gaan op engels en waar nog nederlands staat dit te vertalen. De issues maak ik me niet zo druk over, dat zijn er nog maar twee (of drie met deze erbij) dus die kunnen we desnoods opnieuw maken. De wiki moet toch vertaalt worden en niet alles klopt meer dus dat kan ook wel opnieuw.

**Comment by timvdalen** [comment]
Met een kopie bedoel je nu dus alleen de current state zonder history? Dat vind ik geen goed idee. 
Dat van het vertalen klopt wel inderdaad, dus een kopie maakt niet veel uit, maar ik wil wel voor een kopie met history behoud gaan.

Ferry Timmers reply@reply.github.comschreef:

**Comment by FerryT** [comment]
Nee ik bedoel wel de history erbij maar bv de pdfjes en files die alleen voor het OGO project relevant waren uit de history halen.

**Comment by timvdalen** [comment]
Ah ok. Goed plan. Ik heb een script dat subtrees helemaal kan verwijderen.

Ik heb alleen wel gezien dat bijv Peter af en toe commits heeft gemaakt met wijzigingen in de source en de documentatie, moet even opzoeken hoe dat script daar mee om gaat.

Ferry Timmers reply@reply.github.comschreef:
