### ISSUE TITLE
FPS correction

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#55]
He jongens,

Ik heb het spel eens voor de grap getest op 10 jaar oude pc, een pentium 4 cpu 2.0 ghz 768 mb ram en een Geforce 
4MX 420, 64mb vram. Op zich was het spel nog redelijk speelbaar (standaard 32 fps, met drops naar 10fps), wat ik best een nice prestatie vond :O.

Maar bij deze framedrops merkte ik dat de fps correctie te laat start. Als ik een framedrop heb naar 10fps rijdt hij heel langzaam, dan wordt mijn framerate 32fps en kan ik enorm snel racen. Ik denk dat we een lopend gemiddelde moeten gaan gebruiken voor de fps berekening. Nu nemen we toch een gemiddelde over de voorgaande seconde?

Verder mis ik een priority label: very low in github :P. Ik dacht ik post dit zodat ik dit niet nog een keer vergeet.

**Comment by timvdalen** [comment]
Ah! Dus dat is wat er gebeurde tijdens de presentatie. Toen stond die netdebug nog aan, dus elke keer als er iemand joinde dropte Peter zijn framerate. Daarna kon hij ineens snel lopen.

Label toegevoegd :P

**Comment by KAYLukas** [comment]
Oplossing met glfw:

https://gist.github.com/3003815
