### ISSUE TITLE
Remove empty objects after destruction of headquarters

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#56]
The empty objects, which fill the empty spots of a headquarter are not removed upon destruction of a headquarter.

**Comment by timvdalen** [comment]
I'm working on a fix. Those buildings now get marked as destroyed, but when the game ends, the Terrain loop isn't called anymore so they don't get removed.
I'm actually not so sure if need this, I think we would eventually have some score board at the end of the game (blocking input).
Maybe we can even make like a scoreboard room, a new Game which contains a huge wall we display the scores on.

**Comment by timvdalen** [comment]
This is solved.
