### ISSUE TITLE
RFC: Culling and configs

### ISSUE THREAD

**Issue by KAYLukas** [timvdalen/OGO-2.3#58]
Hello guys,

I'm proposing a culling method. I was able to increase my fps from 30 tot 40 fps by not drawing objects which are behind the camera or 300 units in front of the camera. The best way to do this is too check in the render function of a bounded object after prerender, if the bounding box is visible. This is easily done using the modelview matrix. The culling can even be extended by considering objects to far in the right or left direction. However, while implementing this, I came across a difficulty:

postrender() draws the children and reverts the translations and rotations done by prerender. To implement culling I want to revert the translations and rotations only and not draw the children. Therefore, I propose we split post render up in postrender and renderChildren. In my opinion, this is much cleaner, because it is not clear from the name of postrender that it draws the children.

Furthermore, I propose a namespace config, which contains all variables from the config file. These can then be requested from any part of the program. Furthermore, it would be a good idea to write variables after termination back to the config file, so we can easily keep track of the last state of the namespace config.

**Comment by FerryT** [comment]
Goed bezig Tim. ;)
Issue lijst aan het opschonen? :P
Was een leuk project maar is nu idd wel redelijk dood.

**Comment by timvdalen** [comment]
Haha ja, nieuwe tool die al m'n repos met issues laat zien, werd iets te onoverzichtelijk.

**Comment by FerryT** [comment]
Begrijpelijk :D
